### ISSUE TITLE
ImportError: No module named carla.benchmarks.corl_2017

### ISSUE THREAD

**Issue by abhishektyaagi** [CSLDepend/AVFI#1]
Hi,
I was trying to understand the working of AVFI. I downloaded the repository and built the image with the help of the given dockerfile. To start the fault injection process, I started the carla server and ran the command

`python ./run_CIL.py --host carla_server -p 2000 -c Town01`

But on doing so, I am getting the following error:

`ImportError: No module named carla.benchmarks.corl_2017`

It seems like the client and the server are not able to interact. Is that the case? 

If not, what do you think might be going wrong here?

**Comment by ssbanerje** [comment]
The main CARLA project’s code organization has changed. 

The file that is causing the error is no longer at `carla.benchmarks`. You can find it here: https://github.com/carla-simulator/driving-benchmarks/blob/master/version084/driving_benchmarks/corl2017/corl_2017.py

**Comment by abhishektyaagi** [comment]
Thank you for the quick reply. Are there any other changes that you think might be required to make AVFI work?
