### ISSUE TITLE
How should I run the image after building successfully?

### ISSUE THREAD

**Issue by henryJhonOt** [CSLDepend/AVFI#2]
I've successfully built the image according to the `Dockerfile_x86`
The README.md says, and I quote, 
> We have provided the Dockerfile which will build an image with all
the required packages and dependencies installed. Using this image
is the easiest way to run the CARLA client with the Fault Injection
campaign.
> The self driving agent with the fault injector will run from within
the docker container. The server (world simulator with the AV) has 
to be started separately before running the agent from the docker
container. 
> Make sure both the server and the client are using CARLA 0.8.1

Given the circumstance that I can't find where the carla image is built, how should I run this project?

**Comment by ssbanerje** [comment]
The [CARLA](https://carla.org) server is a separate repo/project.

See [here](https://carla.readthedocs.io/en/stable/) for more details.

**Comment by henryJhonOt** [comment]
> The [CARLA](https://carla.org) server is a separate repo/project.
> 
> See [here](https://carla.readthedocs.io/en/stable/) for more details.

So I still need to install a carla server to run AVFI despite I've built the dockerfile?
Thanks for your help.

**Comment by ssbanerje** [comment]
Yes. This dockerfile is related to the fault injector and a sample controller for the car.

The CARLA project is responsible for simulating the world in which the car will run. So it does physics sim, sensor data sim etc.

These two components are like a server (CARLA) and a client (this project/compiled dockerfile) which communicate with each other over TCP.
